theme: jekyll-theme-cayman

# Site settings
title: Ismaël Aliouat
email: ismaelaliouat@gmail.com
description: Hi, I'm Ismaël Aliouat

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
